development:
  adapter: postgresql
  database: db/development
  encoding: unicode
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production
  pool: 5
  timeout: 5000
